---
title: "asn2139_hw2"
author: "Akanksha Nalatwad"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)

```
## Problem 1

Importing Dataset

```{r}
trash_df=
  read_xlsx(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet="Mr. Trash Wheel",
  range=cell_cols("A:N")) %>% 
      janitor::clean_names () %>% 
     drop_na(dumpster) %>% 
    mutate(
      sports_balls= round(sports_balls),
      sports_balls= as.integer(sports_balls)
    )
```

Read preciptation data for 2017 and 2018

```{r}
precip_2018=
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             sheet="2018 Precipitation",
             skip=1) %>% 
            janitor::clean_names () %>% 
            drop_na(month) %>% 
            mutate(year=2018) %>% 
            relocate(year)

precip_2017=
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             sheet="2017 Precipitation",
             skip=1
             ) %>% 
            janitor::clean_names() %>% 
            drop_na(month) %>% 
            mutate(year=2017) %>% 
            relocate(year)
  
          

```




